apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: voldifqhk-python 
  janus-idp.io/tekton: voldifqhk-python
  backstage.io/kubernetes-id: voldifqhk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: voldifqhk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml